apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
   replicas: 2
   selector:
     matchLabels:
       app: demoapp
       version: blue
   template:
     metadata:
       labels:
         app: demoapp
         version: blue
     spec:
       containers:
       - name: demoapp
         image: dockerimage
         ports:
         - containerPort: 8080